//
// Created by Loeng on 2024/9/11.
//

#ifndef MODERN_COMPILER_IMPLEMENTATION_IN_C_PROG1_H
#define MODERN_COMPILER_IMPLEMENTATION_IN_C_PROG1_H
A_stm prog(void);
#endif //MODERN_COMPILER_IMPLEMENTATION_IN_C_PROG1_H
